# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-12-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='\u6807\u9898')),
                ('content', models.TextField(null=True, verbose_name='\u5185\u5bb9')),
            ],
        ),
    ]
